build:
  stage: build
  image: docker
  interruptible: true
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  parallel:
    matrix:
      - TAG: linux
      - TAG: windows
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t lthn/wallet:$TAG -f .build/docker/$TAG.Dockerfile .
    - docker run -v $(pwd):/build lthn/wallet:$TAG
  artifacts:
    paths:
      - build