name: gui

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install hidapi git openssl zmq libpgm libsodium miniupnpc ldns expat libunwind-headers protobuf qt5 pkg-config
      - run: brew install --build-from-source ./ci/utils/homebrew/boost@169.rb
      - run: git clone --depth=1 --branch=v4.0.4 https://github.com/letheanVPN/blockchain.git lethean
      - name: build
        run: ./build.sh

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: remove bundled boost
        run: sudo rm -rf /usr/local/share/boost
      - name: set apt conf
        run: |
          echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
          echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
          echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
      - name: update apt
        run: sudo apt update
      - name: install lethean dependencies
        run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libprotobuf-dev protobuf-compiler
      - name: install lethean gui dependencies
        run: sudo apt -y install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtqml-models2 qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel qml-module-qt-labs-settings qml-module-qt-labs-platform qml-module-qt-labs-folderlistmodel qttools5-dev-tools qml-module-qtquick-templates2 libqt5svg5-dev libgcrypt20-dev xvfb
      - run: git clone --depth=1 --branch=v4.0.4 https://github.com/letheanVPN/blockchain.git lethean
      - name: build
        run: ./build.sh

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: eine/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb mingw-w64-x86_64-unbound git mingw-w64-x86_64-qt5 mingw-w64-x86_64-libgcrypt
      - run: git clone --depth=1 --branch=v4.0.4 https://github.com/letheanVPN/blockchain.git lethean
      - name: build
        run: ./build.sh


  macos-bundle:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install hidapi openssl zmq libpgm miniupnpc ldns expat libunwind-headers protobuf pkg-config python3 p7zip aria2
      - name: install dependencies
        run: pip3 install defusedxml
      - name: download qt
        run: python3 lethean-gui/.github/qt_helper.py mac_x64 desktop 5.15.2 clang_64 c384008156fe63cc183bade0316828c598ff3e5074397c0c9ccc588d6cdc5aca
        working-directory: ../
      - run: git clone --depth=1 --branch=v4.0.4 https://github.com/letheanVPN/blockchain.git lethean
      - name: build
        run: ./build.sh
      - name: create .tar
        run: tar -cf lethean-wallet-gui.tar lethean-wallet-gui.app
        working-directory: build/release/bin
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: build/release/bin/lethean-wallet-gui.tar


  source-archive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: archive
        run: |
          pip install git-archive-all
          export VERSION="lethean-gui-$(git describe)"
          export OUTPUT="$VERSION.tar"
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
          /home/runner/.local/bin/git-archive-all --prefix "$VERSION/" --force-submodules "$OUTPUT"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT }}
          path: /home/runner/work/letheanVPN/lethean-gui/${{ env.OUTPUT }}wd